apiVersion: v2
appVersion: "0.1"
description: Reference data service for judiciary
name: rd-judicial-api
version: 0.0.23
maintainers:
  - name: Reference Data Team
job:
  concurrencyPolicy: Allow
dependencies:
  - name: java
    version: 4.0.13
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: servicebus
    version: v0.4.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: servicebus.enabled
